### ISSUE TITLE
UX: Modified content within tab

### ISSUE THREAD

**Issue by steveoh** [tony-jones/slack-ui#4]
[Currently there is no visible demarkation](https://github.com/tony-jones/slack-ui/blob/3e796025e03946ac952752a64e8a9b07ddf10694/styles/tabs.less#L65) that the contents of a tab has unsaved changes. This leads to obvious problems. 

I would vote for the new messages circle from the slack app when you have unread messages in a team.

![image](https://cloud.githubusercontent.com/assets/325813/11983501/2a61afcc-a971-11e5-8f60-6e8aced70502.png)

**Comment by tony-jones** [comment]
Thanks @steveoh I will look into it tomorrow. I think that would be a good way to show unsaved changes.

**Comment by steveoh** [comment]
I tried to create the circle, but for some reason the width wouldn't become small enough. sorry i couldn't pr the change. Hopefully you have better luck than I.

**Comment by tony-jones** [comment]
Just made a simple fix for now @steveoh. Just a red circle. Closing as I addressed with this 3ffb997ec15c50c00998c4392fe8067ef9e158d7 checkin. Pushing changes to Atom now.

**Comment by steveoh** [comment]
:+1: thanks!
